language: node_js
node_js:
  - "node"
  
env:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then
      CLANG_VERSION="export CC=gcc && export CXX=g++";
    else
      GCC_VERSION="export CC=gcc-9 && export CXX=g++-9";
    fi
  
os: 
  - linux
  - osx
  - windows
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - cmake
      
osx_image: xcode9.4

before-install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then eval "${CLANG_VERSION}" ; else eval "${GCC_VERSION}" ; fi

install:
  # ${CXX} --version
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]] ; then
      yarn config //set PATH ${PATH};
      yarn config //set DYLIB_LIBRARY_PATH ${DYLIB_LIBRARY_PATH};
      yarn install;
    else
      yarn config set PATH ${PATH};
      yarn config set LD_LIBRARY_PATH ${LD_LIBRARY_PATH};
      yarn install;
    fi

before-scripte:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then eval "${CLANG_VERSION}" ; else eval "${GCC_VERSION}" ; fi
  - export PATH=`pwd`/node_modules/.bin:${PATH}
  - export LD_LIBRARY_PATH=`pwd`/hdf5-1.10.2/dist/lib:${LD_LIBRARY_PATH}
  - export DYLD_LIBRARY_PATH=`pwd`/hdf5-1.10.2/dist/lib:${DYLD_LIBRARY_PATH}
  
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then eval "${CLANG_VERSION}" ; else eval "${GCC_VERSION}" ; fi
  - mkdir -p test/build/src
  - cd test
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then
      make -f Makefile;
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]] ; then
      nmake //F Makefile.win;
    else
      export CC=gcc-9 && export CXX=g++-9;
      ${CXX} --version;
      make -f Makefile;
    fi
  - ./main
